# Generated by Django 4.2.2 on 2023-06-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_user',
            name='address',
        ),
    ]
