# Generated by Django 4.2.2 on 2023-06-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.post'),
        ),
    ]
