# Generated by Django 4.2.2 on 2023-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_application_form_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
