# Generated by Django 4.2.2 on 2023-06-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_application_form_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_form',
            name='post',
        ),
        migrations.AddField(
            model_name='application_form',
            name='Job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.job'),
        ),
    ]
