# Generated by Django 4.2.2 on 2023-07-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_employee_user_about_me_employee_user_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_user',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employer_user',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
