# Generated by Django 4.2.2 on 2023-07-04 01:03

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_employee_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='skills_required',
        ),
        migrations.AlterField(
            model_name='application_form',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=rest_api.models.upload_app_file),
        ),
    ]
