# Generated by Django 4.2.2 on 2023-07-04 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0011_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userObject',
        ),
    ]
