# Generated by Django 4.2.2 on 2023-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_rename_user_userobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobject',
            name='likes',
            field=models.ManyToManyField(blank=True, to='rest_api.userobject'),
        ),
    ]
